syntax = "All"
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 3
quote_style = "AutoPreferSingle"
call_parentheses = "Always"

# 'name()' or 'name ()': Never, Definitions, Calls, o Always
space_after_function_names = "Never"

# Never, FunctionOnly, ConditionalOnly, o Always
collapse_simple_statement = "Always"

[sort_requires]
enabled = true
