return {
   -- Orden de las columnas
   order = { 'diagnostics', 'numbers', 'folds', 'git' },
   disabled = false,
   disabled_ft = {
      'alpha',
      'dashboard',
      'NvimTree',
      'Outline',
      'help',
      'lspinfo',
      'packer',
      'qf',
      'startify',
      'startuptime',
      'vimfiler',
      'vimhelp',
      'viminfo',
      'undotree',
      'lazy',
      'mason',
      'TelescopePrompt',
      'Telescope',
      'toggleterm',
      'diff',
      'fugitiveblame',
      'blink-cmp-menu',
      'blink-cmp-documentation',
      'blink-cmp-signature',
   },
}
